#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

def getList(map, count, path, indentchars, noset=False):
    files = os.listdir(path)
    files = [f for f in files if f[0] is not '.']
    files.sort()

    for f in files:
        child_path = path + "/" + f
        is_file = os.path.isfile(child_path)
        is_last = files.index(f) == len(files)-1
        if is_file:
            print indentchars + (u"└── " if is_last else u"├── ") + f + " ===> " + str(count)
            map[count] = child_path
            count += 1
        else:
            print indentchars + (u"└── " if is_last else u"├── ")+ f
            noset = True if is_last else False
            count = getList(map, count, child_path, indentchars + ("    " if noset else u"│   "), noset)
    return count


def main():
    dir = os.getcwd()
    file_no_map = {}
    print "."
    getList(file_no_map, 1, dir, "", False)
    try:
        no = input("Open file with no: ")
        print file_no_map[no]
        os.system("open " + file_no_map[no])
    except SyntaxError:
        pass


if __name__=="__main__":
    main()
